// AUTO-GENERATED by scripts/hash-assets.mjs — do not edit by hand.
// Re-run `node scripts/hash-assets.mjs` or `npm run build` after adding
// or removing GLBs in public/assets/props/.

export const ASSET_MANIFEST: Record<string, string> = {
  "kenney-bookshelf": "/assets/props/kenney-bookshelf.glb",
  "kenney-chair": "/assets/props/kenney-chair.glb",
  "kenney-lamp": "/assets/props/kenney-lamp.glb",
  "kenney-plant": "/assets/props/kenney-plant.glb",
  "kenney-table": "/assets/props/kenney-table.glb",
};
