// Scans public/assets/props/ for GLB files and writes a typed manifest at
// src/features/playable-world/level/asset-manifest.generated.ts mapping each
// asset ID (filename without extension) to its served public URL.
//
// Run automatically via npm's `prebuild` lifecycle. Safe to run manually
// after dropping new GLBs into public/assets/props/.
//
// Content hashing for forever-cacheable URLs is deferred — for the current
// MVP we serve from public/ with HTTP ETag caching, which is sufficient at
// our scale. When the library grows past a few hundred assets we can extend
// this script to emit content hashes without touching AssetRegistry.

import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const PROJECT_ROOT = join(__dirname, "..");
const PROPS_DIR = join(PROJECT_ROOT, "public", "assets", "props");
const OUT_FILE = join(
  PROJECT_ROOT,
  "src",
  "features",
  "playable-world",
  "level",
  "asset-manifest.generated.ts",
);

function listGlbFiles() {
  if (!existsSync(PROPS_DIR)) return [];
  return readdirSync(PROPS_DIR)
    .filter((f) => extname(f).toLowerCase() === ".glb")
    .sort();
}

function buildManifest(files) {
  return files.map((file) => {
    const id = basename(file, extname(file));
    const publicPath = `/assets/props/${file}`;
    return [id, publicPath];
  });
}

function renderModule(entries) {
  const header =
    "// AUTO-GENERATED by scripts/hash-assets.mjs — do not edit by hand.\n" +
    "// Re-run `node scripts/hash-assets.mjs` or `npm run build` after adding\n" +
    "// or removing GLBs in public/assets/props/.\n\n";
  const lines = entries
    .map(([id, p]) => `  ${JSON.stringify(id)}: ${JSON.stringify(p)},`)
    .join("\n");
  return `${header}export const ASSET_MANIFEST: Record<string, string> = {\n${lines}\n};\n`;
}

function main() {
  const files = listGlbFiles();
  const entries = buildManifest(files);
  const outDir = dirname(OUT_FILE);
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  writeFileSync(OUT_FILE, renderModule(entries), "utf8");
  console.log(`[hash-assets] wrote ${entries.length} entries to ${OUT_FILE}`);
}

main();
