/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaysRouteImport } from './routes/ways'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaysSessionIdRouteImport } from './routes/ways/$sessionId'
import { Route as IndexNextRouteImport } from './routes/index.next'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiQuestionsRouteImport } from './routes/api/questions'
import { Route as WaysSessionIdWorldRouteImport } from './routes/ways/$sessionId/world'
import { Route as ApiSessionsIdRouteImport } from './routes/api/sessions/$id'

const WaysRoute = WaysRouteImport.update({
  id: '/ways',
  path: '/ways',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaysSessionIdRoute = WaysSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => WaysRoute,
} as any)
const IndexNextRoute = IndexNextRouteImport.update({
  id: '/index/next',
  path: '/index/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsRoute = ApiQuestionsRouteImport.update({
  id: '/api/questions',
  path: '/api/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const WaysSessionIdWorldRoute = WaysSessionIdWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => WaysSessionIdRoute,
} as any)
const ApiSessionsIdRoute = ApiSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiSessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ways': typeof WaysRouteWithChildren
  '/api/questions': typeof ApiQuestionsRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/index/next': typeof IndexNextRoute
  '/ways/$sessionId': typeof WaysSessionIdRouteWithChildren
  '/api/sessions/$id': typeof ApiSessionsIdRoute
  '/ways/$sessionId/world': typeof WaysSessionIdWorldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ways': typeof WaysRouteWithChildren
  '/api/questions': typeof ApiQuestionsRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/index/next': typeof IndexNextRoute
  '/ways/$sessionId': typeof WaysSessionIdRouteWithChildren
  '/api/sessions/$id': typeof ApiSessionsIdRoute
  '/ways/$sessionId/world': typeof WaysSessionIdWorldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ways': typeof WaysRouteWithChildren
  '/api/questions': typeof ApiQuestionsRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/index/next': typeof IndexNextRoute
  '/ways/$sessionId': typeof WaysSessionIdRouteWithChildren
  '/api/sessions/$id': typeof ApiSessionsIdRoute
  '/ways/$sessionId/world': typeof WaysSessionIdWorldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ways'
    | '/api/questions'
    | '/api/sessions'
    | '/index/next'
    | '/ways/$sessionId'
    | '/api/sessions/$id'
    | '/ways/$sessionId/world'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ways'
    | '/api/questions'
    | '/api/sessions'
    | '/index/next'
    | '/ways/$sessionId'
    | '/api/sessions/$id'
    | '/ways/$sessionId/world'
  id:
    | '__root__'
    | '/'
    | '/ways'
    | '/api/questions'
    | '/api/sessions'
    | '/index/next'
    | '/ways/$sessionId'
    | '/api/sessions/$id'
    | '/ways/$sessionId/world'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WaysRoute: typeof WaysRouteWithChildren
  ApiQuestionsRoute: typeof ApiQuestionsRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  IndexNextRoute: typeof IndexNextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ways': {
      id: '/ways'
      path: '/ways'
      fullPath: '/ways'
      preLoaderRoute: typeof WaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ways/$sessionId': {
      id: '/ways/$sessionId'
      path: '/$sessionId'
      fullPath: '/ways/$sessionId'
      preLoaderRoute: typeof WaysSessionIdRouteImport
      parentRoute: typeof WaysRoute
    }
    '/index/next': {
      id: '/index/next'
      path: '/index/next'
      fullPath: '/index/next'
      preLoaderRoute: typeof IndexNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions': {
      id: '/api/questions'
      path: '/api/questions'
      fullPath: '/api/questions'
      preLoaderRoute: typeof ApiQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ways/$sessionId/world': {
      id: '/ways/$sessionId/world'
      path: '/world'
      fullPath: '/ways/$sessionId/world'
      preLoaderRoute: typeof WaysSessionIdWorldRouteImport
      parentRoute: typeof WaysSessionIdRoute
    }
    '/api/sessions/$id': {
      id: '/api/sessions/$id'
      path: '/$id'
      fullPath: '/api/sessions/$id'
      preLoaderRoute: typeof ApiSessionsIdRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
  }
}

interface WaysSessionIdRouteChildren {
  WaysSessionIdWorldRoute: typeof WaysSessionIdWorldRoute
}

const WaysSessionIdRouteChildren: WaysSessionIdRouteChildren = {
  WaysSessionIdWorldRoute: WaysSessionIdWorldRoute,
}

const WaysSessionIdRouteWithChildren = WaysSessionIdRoute._addFileChildren(
  WaysSessionIdRouteChildren,
)

interface WaysRouteChildren {
  WaysSessionIdRoute: typeof WaysSessionIdRouteWithChildren
}

const WaysRouteChildren: WaysRouteChildren = {
  WaysSessionIdRoute: WaysSessionIdRouteWithChildren,
}

const WaysRouteWithChildren = WaysRoute._addFileChildren(WaysRouteChildren)

interface ApiSessionsRouteChildren {
  ApiSessionsIdRoute: typeof ApiSessionsIdRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsIdRoute: ApiSessionsIdRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WaysRoute: WaysRouteWithChildren,
  ApiQuestionsRoute: ApiQuestionsRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  IndexNextRoute: IndexNextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
